"""
Task Center data models

Defines Pydantic models for the Task Center module:
- Task, TaskSource, TaskSchedule, TaskExecution, RetryConfig
- TaskExecutionRecord (for scheduled task history)
- Enums: TaskType, TaskStatus, TaskPriority, DeliveryStatus
"""

from datetime import datetime, timezone
from enum import Enum
from typing import Any, Dict, List, Optional

from pydantic import BaseModel, ConfigDict, Field

from flocks.utils.id import Identifier


class TaskType(str, Enum):
    SCHEDULED = "scheduled"
    QUEUED = "queued"
    # TODO: STREAM = "stream" — not yet implemented


class TaskStatus(str, Enum):
    PENDING = "pending"
    QUEUED = "queued"
    RUNNING = "running"
    COMPLETED = "completed"
    FAILED = "failed"
    CANCELLED = "cancelled"
    PAUSED = "paused"


class ExecutionMode(str, Enum):
    AGENT = "agent"
    WORKFLOW = "workflow"


class TaskPriority(str, Enum):
    URGENT = "urgent"
    HIGH = "high"
    NORMAL = "normal"
    LOW = "low"

    @property
    def weight(self) -> int:
        """Higher weight = higher priority, used for queue ordering."""
        return {
            TaskPriority.URGENT: 4,
            TaskPriority.HIGH: 3,
            TaskPriority.NORMAL: 2,
            TaskPriority.LOW: 1,
        }[self]


class DeliveryStatus(str, Enum):
    UNREAD = "unread"
    NOTIFIED = "notified"
    VIEWED = "viewed"


class TaskSource(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    source_type: str = Field(
        "user_conversation",
        alias="sourceType",
        description="user_conversation | system_evolution | scheduled_trigger",
    )
    session_id: Optional[str] = Field(
        None, alias="sessionID",
        description="Session ID where this task was created",
    )
    user_prompt: Optional[str] = Field(
        None, alias="userPrompt",
        description="Original user prompt text",
    )


class TaskSchedule(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    cron: Optional[str] = Field(None, description="Cron expression (for recurring tasks)")
    timezone: str = Field("Asia/Shanghai", description="Timezone")
    next_run: Optional[datetime] = Field(None, alias="nextRun")
    enabled: bool = Field(True)
    cron_description: Optional[str] = Field(
        None, alias="cronDescription",
        description="Human-readable schedule description, e.g. '每天早上9点' or '今晚18:00执行一次'",
    )
    # One-time execution support
    run_once: bool = Field(
        False, alias="runOnce",
        description="If True, this task runs only once and is disabled after execution",
    )
    run_at: Optional[datetime] = Field(
        None, alias="runAt",
        description="Exact UTC datetime for one-time execution (used when run_once=True)",
    )


class TaskExecution(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    session_id: Optional[str] = Field(None, alias="sessionID")
    agent: str = Field("rex", description="Agent that executes this task")
    started_at: Optional[datetime] = Field(None, alias="startedAt")
    completed_at: Optional[datetime] = Field(None, alias="completedAt")
    duration_ms: Optional[int] = Field(None, alias="durationMs")
    result_summary: Optional[str] = Field(None, alias="resultSummary")
    error: Optional[str] = None


class RetryConfig(BaseModel):
    model_config = ConfigDict(populate_by_name=True)

    max_retries: int = Field(3, alias="maxRetries")
    retry_count: int = Field(0, alias="retryCount")
    retry_delay_seconds: int = Field(60, alias="retryDelaySeconds")
    retry_after: Optional[datetime] = Field(
        None, alias="retryAfter",
        description="Persist the retry-after timestamp so retries survive process restarts",
    )


class Task(BaseModel):
    """Core task model — one task = one independent deliverable work unit."""

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(default_factory=lambda: Identifier.descending("task"))
    title: str = Field(..., description="Short task title generated by Rex")
    description: str = Field("", description="Detailed description")
    type: TaskType = Field(TaskType.QUEUED)
    status: TaskStatus = Field(TaskStatus.PENDING)
    priority: TaskPriority = Field(TaskPriority.NORMAL)

    source: TaskSource = Field(default_factory=TaskSource)
    schedule: Optional[TaskSchedule] = None
    execution: Optional[TaskExecution] = None
    delivery_status: DeliveryStatus = Field(
        DeliveryStatus.UNREAD, alias="deliveryStatus",
    )

    # Execution strategy — how this task is executed
    execution_mode: ExecutionMode = Field(
        ExecutionMode.AGENT, alias="executionMode",
    )
    agent_name: str = Field("rex", alias="agentName")
    workflow_id: Optional[str] = Field(None, alias="workflowID")
    skills: List[str] = Field(default_factory=list)
    category: Optional[str] = None

    context: Dict[str, Any] = Field(default_factory=dict)
    retry: Optional[RetryConfig] = Field(default_factory=RetryConfig)
    tags: List[str] = Field(default_factory=list)
    dedup_key: Optional[str] = Field(
        None, alias="dedupKey",
        description="Idempotency key — if set, prevents creating a duplicate active task",
    )

    created_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), alias="createdAt",
    )
    updated_at: datetime = Field(
        default_factory=lambda: datetime.now(timezone.utc), alias="updatedAt",
    )
    created_by: str = Field("rex", alias="createdBy")

    # Convenience helpers -----------------------------------------------

    @property
    def is_terminal(self) -> bool:
        return self.status in (
            TaskStatus.COMPLETED, TaskStatus.FAILED,
            TaskStatus.CANCELLED,
        )

    def touch(self) -> None:
        self.updated_at = datetime.now(timezone.utc)


def build_schedule(
    *,
    run_once: bool = False,
    run_at: Optional[str] = None,
    cron: Optional[str] = None,
    cron_description: Optional[str] = None,
    timezone: str = "Asia/Shanghai",
) -> TaskSchedule:
    """Build a TaskSchedule from raw user/API parameters.

    Raises ValueError on invalid input (missing fields, bad datetime format).
    Callers should catch ValueError and translate to their own error format
    (ToolResult, HTTPException, etc.).
    """
    if run_once:
        if not run_at and not cron:
            raise ValueError(
                "run_at or cron is required for one-time scheduled tasks"
            )
        run_at_dt = None
        if run_at:
            try:
                run_at_dt = datetime.fromisoformat(run_at)
            except (ValueError, TypeError) as exc:
                raise ValueError(
                    f"Invalid run_at datetime format: {run_at!r}. Use ISO 8601."
                ) from exc
        return TaskSchedule(
            cron=cron,
            timezone=timezone,
            cron_description=cron_description,
            run_once=True,
            run_at=run_at_dt,
        )

    if not cron:
        raise ValueError("cron is required for recurring scheduled tasks")
    return TaskSchedule(
        cron=cron,
        timezone=timezone,
        cron_description=cron_description,
        run_once=False,
    )


class TaskExecutionRecord(BaseModel):
    """One execution instance of a scheduled task."""

    model_config = ConfigDict(populate_by_name=True)

    id: str = Field(default_factory=lambda: Identifier.descending("texec"))
    task_id: str = Field(..., alias="taskID")
    status: TaskStatus = Field(TaskStatus.RUNNING)
    started_at: Optional[datetime] = Field(None, alias="startedAt")
    completed_at: Optional[datetime] = Field(None, alias="completedAt")
    duration_ms: Optional[int] = Field(None, alias="durationMs")
    result_summary: Optional[str] = Field(None, alias="resultSummary")
    error: Optional[str] = None
    session_id: Optional[str] = Field(None, alias="sessionID")
    delivery_status: DeliveryStatus = Field(
        DeliveryStatus.UNREAD, alias="deliveryStatus",
    )
